import type { Metadata } from "next";
import {Bowlby_One_SC, DM_Mono} from 'next/font/google';
import { Header } from "@/components/Header";
import "./globals.css";
import { SVGFilters } from "@/components/SVGFilters";
import { Footer } from "@/components/Footer";

const bowlby = Bowlby_One_SC({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bowlby-sc',
  display: 'swap',
})

const dmMono = DM_Mono({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-dm-mono',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bowlby.variable} ${dmMono.variable} antialiased font-mono font-medium text-zinc-800`}
      >
        <main>
          <Header />
        {children}
        <Footer />
        </main>
        <SVGFilters/>
      </body>
    </html>
  );
}
